config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :clients
  get '/categories/:slug', to: 'categories#show', as: :category
  get '/goods/:slug', to: 'goods#show', as: :good
  post '/toggle_good', to: 'carts#toggle_good', as: :toggle_good
  get 'rest_change/:id', to: 'carts#rest_change', as: :rest_change
  get '/cart', to: 'carts#show', as: :cart
  post 'create_order', to: 'orders#create', as: :create_order
  post 'create_comment', to: 'comments#create', as: :create_comment
  get '/news', to: 'news#index', as: :news
  get '/news/:id', to: 'news#show', as: :news_card
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :client, optional: true
  has_many :cart_goods, dependent: :delete_all

  validates :makeshift_id, presence: true, if: ->(cart){ cart.client.blank? }
  validates :client, presence: true, if: ->(cart){ cart.makeshift_id.blank? }

  def self.find_and_update(makeshift_id, client)
    cart = Cart.find_by(makeshift_id: makeshift_id)
    cart.update(client: client) if cart.present?
    return cart
  end

end

app/models/cart_good.rb
class CartGood < ApplicationRecord
  belongs_to :cart
  belongs_to :rest

  validates :count, :max_count, :cart, :rest, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :goods

  validates :title, :slug, :prior, presence: true
  validates :slug, uniqueness: true

  scope :ordered, -> { order(prior: :desc) }
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders,           dependent: :destroy
  has_one :cart,         dependent: :destroy

  validates :email, uniqueness: true
  validates :email, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :client
  belongs_to :good

  validates :text, :client, :good, presence: true
end

app/models/good.rb
class Good < ApplicationRecord
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :good_parameter_variants
  has_many :rests, dependent: :destroy
  has_many :good_images, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :good_images, :allow_destroy => true
  accepts_nested_attributes_for :rests, :allow_destroy => true

  validates :title, :slug, :cost, :categories, :prior, presence: true
  validates :slug, uniqueness: true

  before_validation :prepare_slug

  scope :ordered, -> { order(prior: :desc) }

  def prepare_slug
    unless self.slug.present?
      slug = UrlStringPreparator.slug(self.slug, self.title)
      if Good.find_by(slug: slug).present?
        self.slug = slug + "-#{Good.where("slug like '#{slug}%'").count}"
      else
        self.slug = slug
      end
    end
  end

  def in_stock?
    Rest.where('good_id = ? and rest >= ?', self.id, 1).any?
  end

  def collect_rests
    self.rests.reduce([]) { |arr, rest| arr.push([rest.collect_config, rest.id]) }
  end
end

app/models/good_image.rb
class GoodImage < ApplicationRecord
  belongs_to :good
  validates :image, :good, presence: true
  mount_uploader :image, GoodImageUploader
end

app/models/good_parameter.rb
class GoodParameter < ApplicationRecord
  has_many :good_parameter_variants

  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/news.rb
class News < ApplicationRecord
  validates :title, :image, :text, presence: true
  mount_uploader :image, GoodImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client
  has_many :order_goods, dependent: :destroy
  validates :client, :status, :price, presence: true
end

app/models/order_good.rb
class OrderGood < ApplicationRecord
  belongs_to :order
  belongs_to :rest
end

app/models/rest.rb
class Rest < ApplicationRecord
  belongs_to :good
  has_and_belongs_to_many :good_parameter_variants
  has_many :cart_goods, dependent: :destroy
  accepts_nested_attributes_for :good_parameter_variants, :allow_destroy => true

  validates :rest, :good, :cost, presence: true

  def collect_config
    self.good_parameter_variants.map { |gpv| "#{gpv.good_parameter.title}: #{gpv.title}" }.join(", ")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = get_client_cart
    @cart_goods = @cart.cart_goods
    @price = get_cart_price(@cart)
  end

  def toggle_good
    @rest = Rest.find(params[:rest])
    cart = get_client_cart
    rest_in_cart = rest_in_cart?(@rest.id)
    rest_in_cart ?
        CartGood.find_by(rest: @rest, cart: cart).destroy :
        CartGood.create(rest: @rest, cart: cart, count: 1, max_count: @rest.rest)
    return render json: { success: true, in_cart: !rest_in_cart, cart_price: get_cart_price(cart) }
  end

  def rest_change
    @rest = Rest.find(params[:id])
    return render json: { success: true, cost: @rest.cost, in_cart: rest_in_cart?(@rest.id) }
  end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def show
    @good = Good.find_by(slug: params[:slug])
    @rests = @good.rests
    @images = @good.good_images
    @comments = @good.comments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @goods = Good.ordered.first(12)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all.order(:created_at)
  end

  def show
    @news = News.find_by(id: params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    unless client_signed_in?
      redirect_to new_client_session_path and return
    end
    cart = get_client_cart
    if cart.cart_goods.count < 1
      flash[:error] = order
      redirect_to cart_path and return
    end
    order = Order.new(client: current_client, price: get_cart_price(cart))
    cart.cart_goods.each do |cart_good|
      order.order_goods.push(OrderGood.new(order: order, rest: cart_good.rest))
    end
    if order.save
      cart.cart_goods.destroy_all
      flash[:success] = "Заказ успешно создан"
      FeedbackMailer.order_create_email(order).deliver
      redirect_to root_path and return
    else
      flast[:errors] = order.errors.messages
      redirect_to cart_path and return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/carts/show.html.slim
.wrapper
  ul.cart__cart-goods
    - @cart_goods.each do |cart_good|
      li.cart__cart-good
        = render "shared/cart_catalog_card", cart_good: cart_good
  .cart-price
    span.cart__cart-price = @price
    span = "Р"
  .order-form
    = form_with url: create_order_path, method: :post, id: 'createOrder', local: true do |f|
      = f.submit "Создать заказ", class: 'btn'

app/views/goods/show.html.slim
.wrapper
  .good-card
    .good-card__images
      .good-card__main_image
        = image_tag @images.first.image.url
    .good-card__info
      h3.good-card__title
        = @good.title
      .good-card__description
        = @good.description
      .good-card__cost
        span.good-card__cost-value = @good.in_stock? ? @good.rests.first.cost : @good.cost
        span = "Р"
      - if @good.in_stock?
        .good-card__buy-form
          = form_with url: toggle_good_path, method: :post, class: 'toggleGood', id: 'toggleGood', local: true do |f|
            - if GoodParameterVariant.joins(:rests).where(rests: { id: @good.rests.pluck(:id) }).any?
              = f.select :rest, @good.collect_rests, selected: @good.rests.first.id
            - else
              = f.hidden_field :rest, value: @good.rests.first.id
            = f.submit "#{rest_in_cart?(@good.rests.first.id) ? 'Удалить' : 'В корзину'}", class: 'btn js-good-toggle'
      - else
        = "Нет в наличии"
      section.comments
        h3.h3-title = "Оставьте комментарий о товаре"
        - if client_signed_in?
          = form_with url: create_comment_path, method: :post, id: 'createComment', local: true do |f|
            .form-input
              = f.label :rating, "Рейтинг", class: "form-label"
              = f.number_field :rating, min: 1, max: 5, value: 1, required: true
            .form-input
              = f.label :text, "Комментарий", class: "form-label"
              = f.text_area :text, required: true
            = f.hidden_field :good_id, value: @good.id
            = f.submit 'Отправить', class: "btn"
          .success-hint
          .error-hint
        - else
          = "Для создания комментария "
          = link_to 'войдите', new_client_session_path, class: "active"
          = " или "
          = link_to 'зарегистрируйтесь', new_client_registration_path, class: "active"
      = render "shared/good_comments", comments: @comments